<a href="https://colab.research.google.com/github/Tanbir0095/numpy/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 **# main benefits of numpy array over a list**


1.   Less Memory
2.   Fast
3. Convinient



In [10]:
# import
import numpy as np

In [11]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [12]:
a[0]

1

In [13]:
# create 2D array
a=np.array([[1,2],[3,4],[4,5]])
a

array([[1, 2],
       [3, 4],
       [4, 5]])

In [14]:
# 'ndim' is used to print the dimention
a.ndim

2

In [15]:
# 'itemsize' is used for print byte
a.itemsize

8

In [16]:
a.dtype

dtype('int64')

In [17]:
a = np.array([2.5,2.3])
a.itemsize


8

In [18]:
a.dtype

dtype('float64')

In [19]:
# 'size' is use for count total number of element in a array
a.size

2

In [20]:
# create a array 'zeros((row,columns))
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
# we can also used ones
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
# 'arange()' is for create a array in betwwen the range size
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#arange(start,end,step)
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [24]:
# ' linspace(1,4,10) it will generate 10 numbers between 1 to 4
np.linspace(1,4,10)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [25]:
np.linspace(1,4,20)

array([1.        , 1.15789474, 1.31578947, 1.47368421, 1.63157895,
       1.78947368, 1.94736842, 2.10526316, 2.26315789, 2.42105263,
       2.57894737, 2.73684211, 2.89473684, 3.05263158, 3.21052632,
       3.36842105, 3.52631579, 3.68421053, 3.84210526, 4.        ])

**Reshape **

In [26]:
a = np.array([[1,2],[5,6],[2,3]])
a.shape

(3, 2)

In [27]:
a.reshape(2,3)

array([[1, 2, 5],
       [6, 2, 3]])

In [28]:
# 'ravel' for flatten the array
a.ravel()

array([1, 2, 5, 6, 2, 3])

**Mathemetical operation**

In [29]:
a.min()

1

In [30]:
a.max()

6

In [31]:
a.sum()

19

In [32]:
a

array([[1, 2],
       [5, 6],
       [2, 3]])

In [33]:
# axis=0 for columns and axis=1 for rows
a.sum(axis=0)

array([ 8, 11])

In [34]:
a.sum(axis=1)

array([ 3, 11,  5])

In [35]:
# sqrt for square root the array
np.sqrt(a)

array([[1.        , 1.41421356],
       [2.23606798, 2.44948974],
       [1.41421356, 1.73205081]])

In [37]:
# for standard deviation
np.std(a)

1.7716909687891083

In [38]:
a


array([[1, 2],
       [5, 6],
       [2, 3]])

In [39]:
b = np.array([[2,3],[2,5],[3,6]])
b

array([[2, 3],
       [2, 5],
       [3, 6]])

In [40]:
# add two array
a+b

array([[ 3,  5],
       [ 7, 11],
       [ 5,  9]])

In [41]:
a-b

array([[-1, -1],
       [ 3,  1],
       [-1, -3]])

In [42]:
a*b

array([[ 2,  6],
       [10, 30],
       [ 6, 18]])

In [43]:
a/b

array([[0.5       , 0.66666667],
       [2.5       , 1.2       ],
       [0.66666667, 0.5       ]])